# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from VideoSlider import VideoSlider


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(685, 436)
        mainWindow.setAnimated(True)
        mainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bottomWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomWidget.sizePolicy().hasHeightForWidth())
        self.bottomWidget.setSizePolicy(sizePolicy)
        self.bottomWidget.setStyleSheet("*{\n"
"    background:None;\n"
"}\n"
"#bottomWidget{\n"
"    background-color:rgb(216, 226, 229);\n"
"}")
        self.bottomWidget.setObjectName("bottomWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bottomWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressWidget = QtWidgets.QWidget(self.bottomWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressWidget.sizePolicy().hasHeightForWidth())
        self.progressWidget.setSizePolicy(sizePolicy)
        self.progressWidget.setStyleSheet("")
        self.progressWidget.setObjectName("progressWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.progressWidget)
        self.horizontalLayout.setContentsMargins(12, 4, 12, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startTimeLabel = QtWidgets.QLabel(self.progressWidget)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.horizontalLayout.addWidget(self.startTimeLabel)
        self.videoSlider = VideoSlider(self.progressWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoSlider.sizePolicy().hasHeightForWidth())
        self.videoSlider.setSizePolicy(sizePolicy)
        self.videoSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.videoSlider.setMaximumSize(QtCore.QSize(16777215, 16))
        self.videoSlider.setAutoFillBackground(False)
        self.videoSlider.setStyleSheet("")
        self.videoSlider.setProperty("value", 11)
        self.videoSlider.setSliderPosition(0)
        self.videoSlider.setTracking(True)
        self.videoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.videoSlider.setInvertedAppearance(False)
        self.videoSlider.setInvertedControls(False)
        self.videoSlider.setObjectName("videoSlider")
        self.horizontalLayout.addWidget(self.videoSlider)
        self.endTimeLabel = QtWidgets.QLabel(self.progressWidget)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.horizontalLayout.addWidget(self.endTimeLabel)
        self.verticalLayout.addWidget(self.progressWidget)
        self.controlFrame = QtWidgets.QFrame(self.bottomWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlFrame.sizePolicy().hasHeightForWidth())
        self.controlFrame.setSizePolicy(sizePolicy)
        self.controlFrame.setStyleSheet("#volumeSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background: white;\n"
"    height: 6px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#volumeSlider::sub-page:horizontal {\n"
"    background: rgb(1, 77, 255);\n"
"    border: 1px solid #777;\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#volumeSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #eee, stop:1 #ccc);\n"
"    border: 1px solid #777;\n"
"    width: 10px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#volumeSlider::add-page:horizontal {\n"
"    background: #fff;\n"
"    border: 1px solid #777;\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"}")
        self.controlFrame.setObjectName("controlFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controlFrame)
        self.horizontalLayout_2.setContentsMargins(8, 2, 8, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playButton = QtWidgets.QPushButton(self.controlFrame)
        self.playButton.setMinimumSize(QtCore.QSize(34, 34))
        self.playButton.setMaximumSize(QtCore.QSize(34, 34))
        self.playButton.setBaseSize(QtCore.QSize(30, 30))
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setFlat(True)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_2.addWidget(self.playButton)
        self.stopButton = QtWidgets.QPushButton(self.controlFrame)
        self.stopButton.setMinimumSize(QtCore.QSize(34, 34))
        self.stopButton.setMaximumSize(QtCore.QSize(34, 34))
        self.stopButton.setBaseSize(QtCore.QSize(30, 30))
        self.stopButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setFlat(True)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.previousButton = QtWidgets.QPushButton(self.controlFrame)
        self.previousButton.setMinimumSize(QtCore.QSize(34, 34))
        self.previousButton.setMaximumSize(QtCore.QSize(34, 34))
        self.previousButton.setBaseSize(QtCore.QSize(30, 30))
        self.previousButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon2)
        self.previousButton.setFlat(True)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_2.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(self.controlFrame)
        self.nextButton.setMinimumSize(QtCore.QSize(34, 34))
        self.nextButton.setMaximumSize(QtCore.QSize(34, 34))
        self.nextButton.setBaseSize(QtCore.QSize(30, 30))
        self.nextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon3)
        self.nextButton.setFlat(True)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.playlistButton = QtWidgets.QPushButton(self.controlFrame)
        self.playlistButton.setMaximumSize(QtCore.QSize(34, 34))
        self.playlistButton.setBaseSize(QtCore.QSize(30, 30))
        self.playlistButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/playlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playlistButton.setIcon(icon4)
        self.playlistButton.setIconSize(QtCore.QSize(20, 20))
        self.playlistButton.setFlat(True)
        self.playlistButton.setObjectName("playlistButton")
        self.horizontalLayout_2.addWidget(self.playlistButton)
        self.timelineButton = QtWidgets.QPushButton(self.controlFrame)
        self.timelineButton.setBaseSize(QtCore.QSize(30, 30))
        self.timelineButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/layout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timelineButton.setIcon(icon5)
        self.timelineButton.setIconSize(QtCore.QSize(20, 20))
        self.timelineButton.setAutoDefault(False)
        self.timelineButton.setDefault(False)
        self.timelineButton.setFlat(True)
        self.timelineButton.setObjectName("timelineButton")
        self.horizontalLayout_2.addWidget(self.timelineButton)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.volumeSlider = QtWidgets.QSlider(self.controlFrame)
        self.volumeSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 67)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_2.addWidget(self.volumeSlider)
        self.verticalLayout.addWidget(self.controlFrame)
        self.gridLayout_2.addWidget(self.bottomWidget, 1, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.videoFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoFrame.sizePolicy().hasHeightForWidth())
        self.videoFrame.setSizePolicy(sizePolicy)
        self.videoFrame.setObjectName("videoFrame")
        self.videoLayout = QtWidgets.QGridLayout(self.videoFrame)
        self.videoLayout.setContentsMargins(0, 0, 0, 0)
        self.videoLayout.setSpacing(0)
        self.videoLayout.setObjectName("videoLayout")
        self.gridLayout_2.addWidget(self.videoFrame, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.startTimeLabel.setText(_translate("mainWindow", "00:00:00"))
        self.endTimeLabel.setText(_translate("mainWindow", "00:00:00"))
        self.playButton.setToolTip(_translate("mainWindow", "play/pause"))
        self.stopButton.setToolTip(_translate("mainWindow", "stop"))
        self.previousButton.setToolTip(_translate("mainWindow", "previous"))
        self.nextButton.setToolTip(_translate("mainWindow", "next"))
        self.playlistButton.setToolTip(_translate("mainWindow", "playlist"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
