# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\playlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Playlist(object):
    def setupUi(self, Playlist):
        Playlist.setObjectName("Playlist")
        Playlist.setWindowModality(QtCore.Qt.WindowModal)
        Playlist.resize(240, 220)
        Playlist.setMinimumSize(QtCore.QSize(240, 130))
        Playlist.setMaximumSize(QtCore.QSize(260, 480))
        self.gridLayout = QtWidgets.QGridLayout(Playlist)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalFrame = QtWidgets.QFrame(Playlist)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.verticalFrame)
        self.listView.setMinimumSize(QtCore.QSize(0, 0))
        self.listView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listView.setDragEnabled(True)
        self.listView.setUniformItemSizes(True)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.gridLayout.addWidget(self.verticalFrame, 0, 0, 1, 1)

        self.retranslateUi(Playlist)
        QtCore.QMetaObject.connectSlotsByName(Playlist)

    def retranslateUi(self, Playlist):
        _translate = QtCore.QCoreApplication.translate
        Playlist.setWindowTitle(_translate("Playlist", "Playlist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Playlist = QtWidgets.QWidget()
    ui = Ui_Playlist()
    ui.setupUi(Playlist)
    Playlist.show()
    sys.exit(app.exec_())
